output   = "db/models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "demo"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  blacklist = ["migrations", "casbin_rule"]
